name: Hello GitHub Actions

on:
  workflow_dispatch
  # push:
  #   branches:
  #     - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: 打招呼s
        run: echo "Hello GitHub Actions!"
      - name: 顯示目前時間
        run: date
      - name: 顯示系統資訊
        run: |
          uname -a
          pwd